/**
 * Login status. Shows the status after a login attempt.
 */
export class LoginStatus {
    /**
     * Username of the login attempt.
     */
    username: string = '';
    /**
     * Logged in flag. If it is true, then the user managed to log in.
     */
    logged: boolean = false;
    /**
     * Authentication token generated by the backend.
     */
    token: string = '';
}